"""
Loader for ADK agents from database.

This module loads agents from PostgreSQL database and converts them
to ADK Agent objects that can be used by the ADK web interface.
"""

import os
from typing import List, Dict, Optional
from pathlib import Path
from sqlalchemy.orm import Session
from google.adk.agents import Agent
from src.database import SessionLocal
from src.models import Agent as AgentModel
from tools import calculator, get_current_time


# Tool mapping from database names to actual functions
TOOL_MAP = {
    "calculator": calculator,
    "get_current_time": get_current_time,
}


def get_tools_from_names(tool_names: List[str]) -> List:
    """Convert tool names from database to actual tool functions."""
    tools = []
    for tool_name in tool_names:
        if tool_name in TOOL_MAP:
            tools.append(TOOL_MAP[tool_name])
        else:
            print(f"⚠ Warning: Tool '{tool_name}' not found, skipping")
    return tools


def load_agent_from_db(db_agent: AgentModel) -> Optional[Agent]:
    """Convert a database Agent model to an ADK Agent object."""
    try:
        # Get tools from database
        tool_names = db_agent.tools or []
        tools = get_tools_from_names(tool_names)
        
        # Create ADK Agent
        adk_agent = Agent(
            model=db_agent.model,
            name=db_agent.name,
            description=db_agent.description or "",
            instruction=db_agent.instruction,
            tools=tools,
        )
        
        return adk_agent
    except Exception as e:
        print(f"✗ Erro ao carregar agente '{db_agent.name}': {e}")
        return None


def load_all_agents_from_db(db: Session) -> Dict[str, Agent]:
    """Load all active agents from database and return as ADK Agent objects."""
    agents = {}
    
    # Get all active agents from database
    db_agents = db.query(AgentModel).filter(
        AgentModel.is_active == True
    ).all()
    
    if not db_agents:
        print("⚠ Nenhum agente ativo encontrado no banco de dados")
        return agents
    
    print(f"\n📦 Carregando {len(db_agents)} agente(s) do banco de dados...")
    
    for db_agent in db_agents:
        adk_agent = load_agent_from_db(db_agent)
        if adk_agent:
            # Use the agent name as key, or create a unique key
            agent_key = f"agent_{db_agent.id}"  # Use ID to avoid conflicts
            agents[agent_key] = adk_agent
            print(f"  ✓ {db_agent.name} (ID: {db_agent.id})")
    
    return agents


def create_dynamic_agents_module(db_agents: List[AgentModel], output_dir: Path) -> Path:
    """
    Create a dynamic agents module that ADK can load.
    
    This creates a temporary directory structure that ADK expects,
    with agent.py files containing the agents from the database.
    
    ADK expects: agents/<agent_name>/agent.py
    We'll create one directory per agent from database.
    """
    # Create output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # ADK expects: agents/<agent_name>/agent.py
    # Create agents directory
    agents_base_dir = output_dir / "agents"
    agents_base_dir.mkdir(parents=True, exist_ok=True)
    
    # Create a directory for each agent from database
    # Use agent name (sanitized) as directory name
    if not db_agents:
        # If no agents, create a default directory
        agent_dir = agents_base_dir / "db_agents"
        agent_dir.mkdir(parents=True, exist_ok=True)
        init_file = agent_dir / "__init__.py"
        init_file.write_text("# Auto-generated agents from database\n")
        agent_file = agent_dir / "agent.py"
    else:
        # Use first agent as main agent directory (for root_agent)
        # ADK requires root_agent, so we'll use the first agent
        first_agent = db_agents[0]
        # Sanitize agent name for directory name
        agent_name = first_agent.name.lower().replace(" ", "_").replace("-", "_")
        agent_name = "".join(c for c in agent_name if c.isalnum() or c == "_")
        if not agent_name:
            agent_name = f"agent_{first_agent.id}"
        
        agent_dir = agents_base_dir / agent_name
        agent_dir.mkdir(parents=True, exist_ok=True)
        
        # Create __init__.py
        init_file = agent_dir / "__init__.py"
        init_file.write_text("# Auto-generated agents from database\n")
        
        # Create agent.py with all agents
        agent_file = agent_dir / "agent.py"
    
    # Generate agent.py content
    lines = [
        "# Auto-generated agents from database",
        "# DO NOT EDIT THIS FILE MANUALLY",
        "# This file is regenerated each time the server starts",
        "",
        "import os",
        "import sys",
        "from pathlib import Path",
        "",
        "# Add project root to path",
        "# Structure: .agents_db/agents/<agent_name>/agent.py",
        "# Need to go up 4 levels to reach project root",
        "project_root = Path(__file__).parent.parent.parent.parent.resolve()",
        "project_root_str = str(project_root)",
        "if project_root_str not in sys.path:",
        "    sys.path.insert(0, project_root_str)",
        "",
        "# Also add to PYTHONPATH environment variable",
        "if 'PYTHONPATH' in os.environ:",
        "    if project_root_str not in os.environ['PYTHONPATH']:",
        "        os.environ['PYTHONPATH'] = f\"{project_root_str}:{os.environ['PYTHONPATH']}\"",
        "else:",
        "    os.environ['PYTHONPATH'] = project_root_str",
        "",
        "# Ensure tools can be imported",
        "# Try importing tools with fallback",
        "try:",
        "    from tools import calculator, get_current_time",
        "except ImportError as e:",
        "    # Fallback: ensure project root is in path and try again",
        "    import sys",
        "    if project_root_str not in sys.path:",
        "        sys.path.insert(0, project_root_str)",
        "    # Try absolute import",
        "    try:",
        "        import importlib.util",
        "        tools_spec = importlib.util.spec_from_file_location(",
        "            'tools',",
        "            project_root / 'tools' / '__init__.py'",
        "        )",
        "        tools_module = importlib.util.module_from_spec(tools_spec)",
        "        tools_spec.loader.exec_module(tools_module)",
        "        calculator = tools_module.calculator",
        "        get_current_time = tools_module.get_current_time",
        "    except Exception:",
        "        # Last resort: try direct import with sys.path manipulation",
        "        sys.path.insert(0, project_root_str)",
        "        from tools import calculator, get_current_time",
        "",
        "from dotenv import load_dotenv",
        "from google.adk.agents import Agent",
        "",
        "# Load environment variables",
        "load_dotenv(project_root / '.env')",
        "",
        "# Configure Google API key",
        "GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY', '')",
        "if GOOGLE_API_KEY:",
        "    os.environ['GOOGLE_API_KEY'] = GOOGLE_API_KEY",
        "",
        "# Tool mapping",
        "TOOL_MAP = {",
        "    'calculator': calculator,",
        "    'get_current_time': get_current_time,",
        "}",
        "",
        "# Note: get_current_time requires timezone parameter",
        "# If not provided, it will default to 'America/Sao_Paulo'",
        "",
    ]
    
    # Add each agent from database
    if db_agents:
        for idx, db_agent in enumerate(db_agents):
            # Get tool names and create tool list
            tool_names = db_agent.tools or []
            tool_list = []
            for tool_name in tool_names:
                if tool_name == "calculator":
                    tool_list.append("calculator")
                elif tool_name == "get_current_time":
                    tool_list.append("get_current_time")
            
            # Create agent variable name
            agent_var_name = f"agent_{db_agent.id}" if db_agent.id else f"agent_{idx}"
            
            # Escape strings for Python code
            description = (db_agent.description or "").replace("'", "\\'").replace("\n", "\\n")
            instruction = db_agent.instruction.replace("'", "\\'").replace("\n", "\\n")
            model = db_agent.model.replace("'", "\\'")
            
            # Sanitize agent name for ADK (must be valid identifier)
            # ADK requires: start with letter/underscore, only letters/digits/underscores
            # Remove accents and special characters
            import unicodedata
            agent_name_sanitized = unicodedata.normalize('NFD', db_agent.name)
            agent_name_sanitized = ''.join(c for c in agent_name_sanitized if unicodedata.category(c) != 'Mn')
            agent_name_sanitized = agent_name_sanitized.lower().replace(" ", "_").replace("-", "_")
            agent_name_sanitized = "".join(c for c in agent_name_sanitized if c.isalnum() or c == "_")
            if not agent_name_sanitized or not (agent_name_sanitized[0].isalpha() or agent_name_sanitized[0] == "_"):
                # If name doesn't start with letter/underscore, prefix with agent_
                agent_name_sanitized = f"agent_{agent_name_sanitized}" if agent_name_sanitized else f"agent_{db_agent.id}"
            
            # Add agent definition
            lines.append(f"# Agent: {db_agent.name} (ID: {db_agent.id})")
            lines.append(f"{agent_var_name} = Agent(")
            lines.append(f"    model='{model}',")
            lines.append(f"    name='{agent_name_sanitized}',")
            lines.append(f"    description='{description}',")
            lines.append(f"    instruction='''{instruction}''',")
            
            # Add tools
            if tool_list:
                tools_str = ", ".join(tool_list)
                lines.append(f"    tools=[{tools_str}],")
            else:
                lines.append(f"    tools=[],")
            
            lines.append(f")")
            lines.append("")
        
        # Use first agent as root_agent (required by ADK)
        first_agent_var = f"agent_{db_agents[0].id}" if db_agents[0].id else "agent_0"
        lines.append("# Root agent (required by ADK)")
        lines.append(f"root_agent = {first_agent_var}")
    else:
        # Default root_agent if no agents in database
        lines.append("# Default root agent (no agents in database)")
        lines.append("root_agent = Agent(")
        lines.append("    model='gemini-2.0-flash-exp',")
        lines.append("    name='root_agent',")
        lines.append("    description='Default agent - no agents found in database',")
        lines.append("    instruction='You are a helpful assistant. Please add agents to the database to use this system.',")
        lines.append("    tools=[],")
        lines.append(")")
    
    # Write agent.py
    agent_file.write_text("\n".join(lines))
    
    # Create individual directories for each agent so they appear in ADK dropdown
    # ADK lists each subdirectory in agents/ as a separate agent
    if db_agents and len(db_agents) > 1:
        for db_agent in db_agents[1:]:  # Skip first (already created above)
            # Sanitize agent name for directory name
            agent_name = db_agent.name.lower().replace(" ", "_").replace("-", "_")
            agent_name = "".join(c for c in agent_name if c.isalnum() or c == "_")
            if not agent_name:
                agent_name = f"agent_{db_agent.id}"
            
            # Avoid duplicate if name matches first agent
            if agent_name == agent_dir.name:
                agent_name = f"{agent_name}_{db_agent.id}"
            
            individual_agent_dir = agents_base_dir / agent_name
            individual_agent_dir.mkdir(parents=True, exist_ok=True)
            
            # Create __init__.py
            individual_init = individual_agent_dir / "__init__.py"
            individual_init.write_text("# Auto-generated agent from database\n")
            
            # Create agent.py with single agent as root_agent
            individual_agent_file = individual_agent_dir / "agent.py"
            
            # Generate content for individual agent
            tool_names = db_agent.tools or []
            tool_list = []
            for tool_name in tool_names:
                if tool_name == "calculator":
                    tool_list.append("calculator")
                elif tool_name == "get_current_time":
                    tool_list.append("get_current_time")
            
            description = (db_agent.description or "").replace("'", "\\'").replace("\n", "\\n")
            instruction = db_agent.instruction.replace("'", "\\'").replace("\n", "\\n")
            model = db_agent.model.replace("'", "\\'")
            
            # Sanitize agent name for ADK (must be valid identifier)
            # Remove accents and special characters
            import unicodedata
            agent_name_sanitized = unicodedata.normalize('NFD', db_agent.name)
            agent_name_sanitized = ''.join(c for c in agent_name_sanitized if unicodedata.category(c) != 'Mn')
            agent_name_sanitized = agent_name_sanitized.lower().replace(" ", "_").replace("-", "_")
            agent_name_sanitized = "".join(c for c in agent_name_sanitized if c.isalnum() or c == "_")
            if not agent_name_sanitized or not (agent_name_sanitized[0].isalpha() or agent_name_sanitized[0] == "_"):
                agent_name_sanitized = f"agent_{agent_name_sanitized}" if agent_name_sanitized else f"agent_{db_agent.id}"
            
            individual_lines = [
                "# Auto-generated agent from database",
                "# DO NOT EDIT THIS FILE MANUALLY",
                "",
                "import os",
                "import sys",
                "from pathlib import Path",
                "",
                "# Add project root to path",
                "project_root = Path(__file__).parent.parent.parent.parent.resolve()",
                "project_root_str = str(project_root)",
                "if project_root_str not in sys.path:",
                "    sys.path.insert(0, project_root_str)",
                "",
                "# Also add to PYTHONPATH environment variable",
                "if 'PYTHONPATH' in os.environ:",
                "    if project_root_str not in os.environ['PYTHONPATH']:",
                "        os.environ['PYTHONPATH'] = f\"{project_root_str}:{os.environ['PYTHONPATH']}\"",
                "else:",
                "    os.environ['PYTHONPATH'] = project_root_str",
                "",
                "# Ensure tools can be imported",
                "try:",
                "    from tools import calculator, get_current_time",
                "except ImportError as e:",
                "    import sys",
                "    if project_root_str not in sys.path:",
                "        sys.path.insert(0, project_root_str)",
                "    try:",
                "        import importlib.util",
                "        tools_spec = importlib.util.spec_from_file_location(",
                "            'tools',",
                "            project_root / 'tools' / '__init__.py'",
                "        )",
                "        tools_module = importlib.util.module_from_spec(tools_spec)",
                "        tools_spec.loader.exec_module(tools_module)",
                "        calculator = tools_module.calculator",
                "        get_current_time = tools_module.get_current_time",
                "    except Exception:",
                "        sys.path.insert(0, project_root_str)",
                "        from tools import calculator, get_current_time",
                "",
                "from dotenv import load_dotenv",
                "from google.adk.agents import Agent",
                "",
                "# Load environment variables",
                "load_dotenv(project_root / '.env')",
                "",
                "# Configure Google API key",
                "GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY', '')",
                "if GOOGLE_API_KEY:",
                "    os.environ['GOOGLE_API_KEY'] = GOOGLE_API_KEY",
                "",
                f"# Agent: {db_agent.name} (ID: {db_agent.id})",
                "root_agent = Agent(",
                f"    model='{model}',",
                f"    name='{agent_name_sanitized}',",
                f"    description='{description}',",
                f"    instruction='''{instruction}''',",
            ]
            
            if tool_list:
                tools_str = ", ".join(tool_list)
                individual_lines.append(f"    tools=[{tools_str}],")
            else:
                individual_lines.append(f"    tools=[],")
            
            individual_lines.append(")")
            
            individual_agent_file.write_text("\n".join(individual_lines))
    
    return agent_dir


def sync_agents_from_db(output_dir: Optional[Path] = None) -> Path:
    """
    Sync agents from database to a directory structure that ADK can use.
    
    This function:
    1. Loads all active agents from the database
    2. Creates a temporary directory structure
    3. Generates agent.py files that ADK can load
    
    Returns the path to the generated agents directory.
    """
    if output_dir is None:
        # Use a temporary directory in the project root
        project_root = Path(__file__).parent.parent
        output_dir = project_root / ".agents_db"
    
    # Create database session
    db = SessionLocal()
    try:
        # Get all active agents from database directly
        db_agents = db.query(AgentModel).filter(
            AgentModel.is_active == True
        ).order_by(AgentModel.created_at.desc()).all()
        
        if not db_agents:
            print("⚠ Nenhum agente ativo encontrado no banco de dados")
            print("  Crie agentes usando a API REST em http://localhost:8001/docs")
        
        # Create dynamic agents module
        agent_dir = create_dynamic_agents_module(db_agents, output_dir)
        
        print(f"\n✓ Agentes sincronizados para: {agent_dir}")
        print(f"  Total de agentes: {len(db_agents)}")
        return agent_dir
        
    finally:
        db.close()


if __name__ == "__main__":
    # Test loading agents
    print("=" * 60)
    print("Testando carregamento de agentes do banco")
    print("=" * 60)
    
    agent_dir = sync_agents_from_db()
    print(f"\n✓ Diretório de agentes criado: {agent_dir}")

