# Auto-generated agent from database
# DO NOT EDIT THIS FILE MANUALLY

import os
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent.resolve()
project_root_str = str(project_root)
if project_root_str not in sys.path:
    sys.path.insert(0, project_root_str)

# Also add to PYTHONPATH environment variable
if 'PYTHONPATH' in os.environ:
    if project_root_str not in os.environ['PYTHONPATH']:
        os.environ['PYTHONPATH'] = f"{project_root_str}:{os.environ['PYTHONPATH']}"
else:
    os.environ['PYTHONPATH'] = project_root_str

# Ensure tools can be imported
try:
    from tools import calculator, get_current_time
    # Note: MCP tools are loaded dynamically at runtime
    # They are not imported here as they require user-specific clients
except ImportError as e:
    import sys
    if project_root_str not in sys.path:
        sys.path.insert(0, project_root_str)
    try:
        import importlib.util
        tools_spec = importlib.util.spec_from_file_location(
            'tools',
            project_root / 'tools' / '__init__.py'
        )
        tools_module = importlib.util.module_from_spec(tools_spec)
        tools_spec.loader.exec_module(tools_module)
        calculator = tools_module.calculator
        get_current_time = tools_module.get_current_time
    except Exception:
        sys.path.insert(0, project_root_str)
        from tools import calculator, get_current_time

from dotenv import load_dotenv
from google.adk.agents import Agent

# Load environment variables
load_dotenv(project_root / '.env')

# Configure Google API key
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY', '')
if GOOGLE_API_KEY:
    os.environ['GOOGLE_API_KEY'] = GOOGLE_API_KEY

# Import context hooks for automatic Redis integration
try:
    from src.services.adk_context_hooks import inject_context_into_agent
    CONTEXT_ENABLED = True
except ImportError:
    CONTEXT_ENABLED = False
    inject_context_into_agent = None

# Agent: Analista de Notícias - Tavily (ID: 10)
root_agent = Agent(
    model='openai/gpt-4o-mini',
    name='analista_de_noticias___tavily',
    description='Analista especializado em buscar e analisar notícias em tempo real. Fornece resumos, análises e contexto sobre eventos atuais.',
    instruction='''Você é um analista de notícias experiente. Quando solicitado:\n\n1. Busque as notícias mais recentes sobre o tópico usando a ferramenta web_search\n2. Analise múltiplas fontes para ter uma visão completa\n3. Identifique os pontos principais e tendências\n4. Forneça contexto histórico quando relevante\n5. Seja imparcial e apresente diferentes perspectivas\n6. Cite todas as fontes com data e URL\n7. Destaque informações conflitantes entre fontes\n\nFormato de resposta ideal:\n- Resumo executivo (2-3 frases)\n- Pontos principais (bullet points)\n- Análise detalhada\n- Fontes consultadas (com URLs)''',
    tools=[web_search],
)

# Inject context into agent if enabled
if CONTEXT_ENABLED and inject_context_into_agent:
    try:
        inject_context_into_agent(root_agent)
    except Exception as e:
        print(f'⚠ Warning: Could not inject context into root_agent: {e}')